### ISSUE TITLE
Duplicate entry in result.hdf5

### ISSUE THREAD

**Issue by kwnminho** [QuantumQuadrate/CsPyController#12]
'experiments\iterations' node and '\iterations' node seem to have identical data entries, as shown in the attachment. Is it for a reason for a bug? Consolidating these will save space.

![duplicate entry](https://user-images.githubusercontent.com/15185440/28385591-509fe514-6c8e-11e7-885f-c3db38a1f2c7.png)

**Comment by c-poole** [comment]
This is the result of a hard link where two paths in the HDF5 file point to the same data. The data is not stored twice, so there isn't anything to be gained by only allowing access via one path. I'm not sure of the specific reasoning for having this in the first place, but it definitely has to do with the optimizer. Closing for now since there isn't actually data duplication.
